### ISSUE TITLE
Could not find dev.baseio.slackcrypto:encryptionlib:1.0.

### ISSUE THREAD

**Issue by Savrov** [oianmol/SlackComposeMultiplatform#31]
Hello, I followed step-by-step instructions but still have an issue with setting up and running this repo. It fails with 

> Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find dev.baseio.slackcrypto:encryptionlib:1.0.
> Searched in the following locations:
>   - https://dl.google.com/dl/android/maven2/dev/baseio/slackcrypto/encryptionlib/1.0/encryptionlib-1.0.pom
>   - file:/Users/savrov/.m2/repository/dev/baseio/slackcrypto/encryptionlib/1.0/encryptionlib-1.0.pom
>   - https://repo.maven.apache.org/maven2/dev/baseio/slackcrypto/encryptionlib/1.0/encryptionlib-1.0.pom
> Required by:
>     project :commoncomposeui > project :slack_data_layer

Can you pls check if it compiles with "clean" workspace?

**Comment by oianmol** [comment]
Yes, check the readme first, I have mentioned of this lib https://github.com/oianmol/capillary-kmp in the list of dependent project, which needs to be built and installed on mavenLocal() . 🥂  👍🏼
